# FROM Intruction
FROM alpine:3

# LABEL Intruction
LABEL author="Apekking"
LABEL company="IF" website="https://www.IF.com"

# RUN Instruction
RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

# CMD
CMD cat "hello/world.txt"